fullnameOverride: grafana

resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: false

adminUser: admin
adminPassword: pod-investigator-demo

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query:16686
        isDefault: true
        editable: true
